[package]
name = "autoraw-core"
version = "0.9.3"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rawler = { path = "vendor/rawler", default-features = false }
kamadak-exif = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
png = "0.17"
jpeg-encoder = "0.6"
tiff = "0.9"

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "1", default-features = false, features = ["rng-getrandom"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
